### ISSUE TITLE
Please release v2.0.1

### ISSUE THREAD

**Issue by kron4eg** [gomodules/jsonpatch#21]
By looking at https://github.com/gomodules/jsonpatch/commit/e8422f09d27ee2c8cfb2c7f8089eb9eeb0764849 It seems like you've moved v2.0.0 tag, which is very unfortunate and should be avoided.

The problem is that proxy.golang.org already captured original v2.0.0 tag so now we have a situation when having 
`GOPROXY=https://proxy.golang.org` gomods get `lHNQverf0+Gm1TbSbVIDWVXOhZ2FpZopxRqpr2uIjs4=` hash of the module
and with `GOPROXY=direct` gomods getting `OyHbl+7IOECpPKfVK42oFr6N7+Y2dR+Jsb/IiDV3hOo=`.

To resolve the situation please tag v2.0.1, and please never ever move tags between commits.

Example of affected go.sum file: https://github.com/kubernetes-sigs/cluster-api/pull/1217

**Comment by tamalsaha** [comment]
I have applied v2.0.1 tag. Please check. Sorry about the inconvenience. I am still learning about go mod.

xref: https://github.com/kubernetes/test-infra/pull/13918

Please reopen if there are new issues.

**Comment by fejta** [comment]
Thanks so much!

**Comment by kron4eg** [comment]
Can confirm, for the v2.0.1 now hash is the same using `GOPROXY=direct` or `GOPROXY=https://proxy.golang.org`. Back to normal! Thanks.
